/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2d1600",
        "tertiary-fixed": "#ffdcc0",
        "surface": "#0a141e",
        "outline": "#859490",
        "surface-dim": "#0a141e",
        "surface-container-highest": "#2c3641",
        "primary": "#57f1db",
        "inverse-primary": "#006b5f",
        "on-secondary-fixed-variant": "#004c69",
        "on-secondary-fixed": "#001e2c",
        "background": "#0a141e",
        "on-error": "#690005",
        "primary-fixed-dim": "#3cddc7",
        "secondary-container": "#00a6e0",
        "on-background": "#d9e3f2",
        "on-tertiary-container": "#744000",
        "on-primary-fixed": "#00201c",
        "error-container": "#93000a",
        "surface-variant": "#2c3641",
        "on-secondary-container": "#00374d",
        "on-surface-variant": "#bacac5",
        "on-primary": "#003731",
        "inverse-on-surface": "#27313c",
        "secondary-fixed": "#c4e7ff",
        "secondary": "#7bd0ff",
        "surface-container-high": "#212b35",
        "tertiary-container": "#ffac5a",
        "surface-tint": "#3cddc7",
        "surface-container-low": "#121c27",
        "on-primary-fixed-variant": "#005047",
        "inverse-surface": "#d9e3f2",
        "on-primary-container": "#00574d",
        "surface-container": "#17202b",
        "on-surface": "#d9e3f2",
        "surface-bright": "#303a45",
        "on-secondary": "#00354a",
        "tertiary": "#ffd1aa",
        "surface-container-lowest": "#050f19",
        "secondary-fixed-dim": "#7bd0ff",
        "outline-variant": "#3c4a46",
        "tertiary-fixed-dim": "#ffb875",
        "on-tertiary-fixed-variant": "#6b3b00",
        "error": "#ffb4ab",
        "on-tertiary": "#4b2800",
        "on-error-container": "#ffdad6",
        "primary-container": "#2dd4bf",
        "primary-fixed": "#62fae3",
        // Additional utility colors used in CSS
        "success_green": "#22c55e",
      },
      fontFamily: {
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
    },
  },
  plugins: [],
};
